### ISSUE TITLE
Need help?

### ISSUE THREAD

**Issue by reitlepax** [hello-pangea/dnd#330]
Hi @100terres,

First of all, thank you for your effort! 

I would love to start contributing and help giving a second life to the beautiful dnd project. What do you think would be the best channel to discuss possible contributions? Maybe a discord server / github discussions?

Let me know what you think.

Cheers

**Comment by will-stone** [comment]
Hi @100terres,

I'd also like to say thank you for keeping the fire burning 😊 One of my projects, [Browserosaurus](https://browserosaurus.com/), uses RBDnD and I only found out yesterday that it's no longer maintained when I tried upgrading to R18. So I'm eagerly watching your R18 issue thread.

To put my voice forward I would please ask you _not_ to use [ Discord on OSS projects](https://drewdevault.com/2021/12/28/Dont-use-Discord-for-FOSS.html) 😭 Turning on GitHub's discussions would be my vote, as it keeps all the discussion under one roof.

Also, how do you feel about turning on GitHub's Sponsors? For those of us who do not have the time to dig deep into the code, but would like to support the project however we can.

Thanks again,

Will.

**Comment by 100terres** [comment]
Hi @reitlepax and @will-stone :slightly_smiling_face: 

Sorry for this late response. I took a week off, but I’m back!

I’m really happy to see your interest in this repository/project! :slightly_smiling_face: 

I’ll try to address this issue and investigate how we could leverage GitHub Discussions feature to discuss possible contributions :slightly_smiling_face: 

Stay tuned!

**Comment by 100terres** [comment]
Hi @will-stone, 

Regarding this :point_down: 

> Also, how do you feel about turning on GitHub's Sponsors? For those of us who do not have the time to dig deep into the code, but would like to support the project however we can.

That’s a good question and I haven’t thought about it! I’ll see how we could open the door for financial contributions :coffee:

**Comment by AntonOfTheWoods** [comment]
@100terres , things seem to have completely frozen for over a month. Have you had some external issues or have you moved on to other things? If you are just busy, is there anyone else who could keep an eye on the repo so that PRs still get comments?

**Comment by Xhale1** [comment]
If y'all ever need someone to take over this library let me know, we use it extensively at work and I'd love to help maintain it.

**Comment by kerams** [comment]
Time to fork it again it would seem.

**Comment by Xhale1** [comment]
It had been a while so I made a new fork over at [@hello-pangea/dnd](https://github.com/hello-pangea/dnd).

I got it working to support React 18 and React strict mode in case anyone here is interested 👍

**Comment by Xhale1** [comment]
Help has arrived :)

This library is now co-maintained under the Pangea organization. I'm really excited about next steps for this library :)
