### ISSUE TITLE
Small suggestion for "Not for everyone" section in README/docs

### ISSUE THREAD

**Issue by calebmsword** [hello-pangea/dnd#363]
Hi, thank you so much for creating this fork. I really like react-beautiful-dnd.

I have a recommendation for the documentation. You can see in [this issue](https://github.com/atlassian/react-beautiful-dnd/issues/316), as well as many others like it, that the library does not currently support grid layouts. It's clear from a discussion in threads like these that grid layouts are a relatively common use case, and yet the documentation doesn't make it clear that the library can't do it, leading many to waste time learning the library before having to use another.

I think it would be a good idea in the "Not for everyone" section **to make it extremely clear that the library does not support lists with grid layouts**. Or, of course, someone could introduce that feature in this fork 😁

**Comment by 100terres** [comment]
@calebmsword Thank you for opening this issue! It's done :heavy_check_mark: @Xhale1 added your suggestion to the "Not for everyone" section. https://github.com/hello-pangea/dnd/pull/418

If you see more improvements we could do to the docs or the library itself, do not hesitate to open new issues! :slightly_smiling_face:
