### ISSUE TITLE
Unexpected behavior in horizontal dragging

### ISSUE THREAD

**Issue by Jobs-Chen** [hello-pangea/dnd#385]
I added `flex-wrap: wrap;` to this elemen, make it multiline: 
<img width="1492" alt="image" src="https://user-images.githubusercontent.com/33348656/173971745-3c6eaae6-6869-44c0-80d6-f958aa551002.png">
but when I drag it: 
<img width="1323" alt="image" src="https://user-images.githubusercontent.com/33348656/173972966-9454d212-7029-4fed-a150-8b2bbc02ab2a.png">
The remaining elements moved together, how do I fix it!

**Comment by Xhale1** [comment]
This library currently does not support grid layouts, though it is on the roadmap. For now only vertical and horizontal lists without wrapping are supported.

**Comment by LvChengbin** [comment]
Are there any update about this feature?

**Comment by 0Chan-smc** [comment]
Any progress?
