### ISSUE TITLE
New organization and maintainer :tada: 

### ISSUE THREAD

**Issue by 100terres** [hello-pangea/dnd#408]
Hello fellow GitHubers :wave: 

As some of you might have noticed, it can be difficult to manage a complex open source project alone and it can have an impact on how long it takes to fix issues. Like for the issue with [react 18](https://github.com/hello-pangea/dnd/issues/293)! Again sorry to have kept you waiting for weeks without any answer. :disappointed:

To make sure it doesn't happen again and to help with all the work ahead of us on this project, we are welcoming a new maintainer @Xhale1 :tada: Thanks to him we have a working version with [react 18](https://github.com/react-forked/dnd/issues/293). (I love the open source community :heart:)

We also plan in the future (sooner than late) to give second life to other un-maintained projects we like and want to keep alive. Some of those projects might not be react related. For this reason we'll rename and move the project to a new organization. This organization is named hello-pangea! If you want new feature and bug fixes, you should plan to migrate to `@hello-pangea/dnd`. The migration will be as simple as doing a find and replace!

If you want to be a part of this new adventure let us know on discord :point_right: https://discord.gg/zKhPpmvCEv

Thank you for your support!

Here's a rough list of what's needed to begin this new chapter:

- [x] add new maintainer @Xhale1 :tada: 
- [x] add [discord join link](https://discord.gg/zKhPpmvCEv)
- [x] change package name references from `@react-forked/dnd` to `@hello-pangea/dnd`
- [x] change github path references from `https://github.com/react-forked/dnd` to `https://github.com/hello-pangea/dnd`
- [x] rename existing [`hello-pangea/dnd`](https://github.com/hello-pangea/dnd) repo to [`hello-pangea/dnd-old`](https://github.com/hello-pangea/dnd-old)
- [x] transfert the ownership of this repo to [hello-pangea org](https://github.com/hello-pangea)
- [x] change domain name from `dnd.react-forked.com` to `dnd.hellopangea.com`
- [x] grant repo access to circleci @Xhale1 
- [x] make sure circleci works
- [x] make sure all actions continue to work (except circleci and netlify)
- [x] drop netlify
- [x] add vercel @Xhale1 
- [x] merge pr containing all the change related to the transfert
- [x] write a blog post about the release, the new name and the new team member! Blog post available here: https://dev.to/100terres/whats-up-with-rfd-578a
- [x] release major version 16.0.0
- [x] deprecate [`@react-forked/dnd`](https://www.npmjs.com/package/@react-forked/dnd) on npm to let people know they should use `@hello-pangea/dnd` instead of `@react-forked/dnd` mentioning the blog post (using [npm deprecate command](https://docs.npmjs.com/cli/v8/commands/npm-deprecate))
- [x] let people know on react-beautiful-dnd repo what's happening

**Comment by Xhale1** [comment]
LGTM

Super excited for the future of this repo :)

**Comment by 100terres** [comment]
Blog post is live: https://dev.to/100terres/whats-up-with-rfd-578a

**Comment by The-Code-Monkey** [comment]
+1 thanks for this hit the react 18 error today and this was a super simple swap out helped a ton.
