### ISSUE TITLE
Horizontal scroll issue

### ISSUE THREAD

**Issue by synapse** [hello-pangea/dnd#420]
Hey guys, it seams the after a certain number of columns the placeholder does not work properly. Any idea what could it be?

Edit: the actual number is 6, cannot drop a column after the 6th one

### Expected behavior
To scroll and create a space for dropping just as it happens for the 2/3 columns

### Actual behavior
After a certain number of columns the placeholder does not seams be working any more

### What version of `React` are you using?
^18.2.0

### What version of `@hello-pangea/dnd` are you running?
^16.0.0

### What browser are you using?
Electron

### Demo
https://www.veed.io/view/4943c614-68ef-4a0b-afd1-cc8c6b315fcb

**Comment by synapse** [comment]
Closing this one since it was just a CSS problem

**Comment by v3rron** [comment]
Could you please share how it was resolved?
I'm having the same issue with a very heavy table, where `<tbody>` is the `Droppable` area and the placeholder being the last `<tr>` element. 
I am not able to pinpoint the problem why it's not working.
Is there a documentation of a CSS requirement for it to work properly?
