### ISSUE TITLE
Support Material UI Stacks

### ISSUE THREAD

**Issue by Darhagonable** [hello-pangea/dnd#433]
### Description
Material UI is one of the most used React component libs out there and its very common to be using their [Stack Component](https://mui.com/material-ui/react-stack/) in ones layouts. Would be great if hello-pangea/dnd could support using dnd together with Stack component without any jumping/snapping.

I think the big problem is that dnd doesn't handle it well when first or last child doesn't have same margins as the other draggables.

This is only a problem for the first item in the list.

### Demo
https://codesandbox.io/s/mui-dnd-stack-19mvpi?file=/demo.tsx

**Comment by 100terres** [comment]
Hi @Darhagonable :wave: 

Thank you for opening this ticket!

Could you provide us more details using a live [CodeSandbox](https://codesandbox.io/) example of the issue you're describing?

**Comment by Darhagonable** [comment]
@100terres I have now added a codesandbox of the issue in the OP

**Comment by 100terres** [comment]
We won't be able to cover this specific use case. I would recommand not using the Stack component with this library.
