### ISSUE TITLE
Support for defaultProps will be removed from memo components

### ISSUE THREAD

**Issue by songhobby** [hello-pangea/dnd#436]
react_devtools_backend.js

Warning: Connect(Droppable): Support for defaultProps will be removed from memo components in a future major release. Use JavaScript default parameters instead.

**Comment by Xhale1** [comment]
Thanks for mentioning this. It's related to using `connected` components from redux instead of hooks, which we will be addressing soon. In the meantime, this warning is harmless.

**Comment by kulame** [comment]
Has a new version been released? I am also encountering this warning
