### ISSUE TITLE
Website not working

### ISSUE THREAD

**Issue by enisdenjo** [hello-pangea/dnd#598]
The repo's about website is not working: https://dnd.hellopangea.com.

BTW, thanks for creating and maintaining this project - I was a big fan of react-beautiful-dnd but it lacked many things that are all fixed and covered here - big love 🙏 .

**Comment by Xhale1** [comment]
Fixed! I recently transferred our domain from Google Domain to Cloudflare due to Google Domains being aquired by Squarespace.
