### ISSUE TITLE
Support redux 5

### ISSUE THREAD

**Issue by AntonOfTheWoods** [hello-pangea/dnd#744]
### Description

Currently it appears that only redux 4 and react-redux 8 are supported, but more recent versions have now been released.

**Comment by ahadcove** [comment]
Yes please!

**Comment by 100terres** [comment]
Hi @AntonOfTheWoods, thank you for bringing this to our attention. I'll see what we can do to support the latest version.

**Comment by 100terres** [comment]
related to: https://github.com/hello-pangea/dnd/pull/731

**Comment by Xhale1** [comment]
I adopted redux 5 at work and everything appears to be working. v5 also had very little breaking changes: https://github.com/reduxjs/redux/releases/tag/v5.0.0

@100terres I think we might be able to widen the dependency range to include 5.x.y with fairly little fuss

**Comment by 100terres** [comment]
I'll try to have a look at this during the weekend.

**Comment by 100terres** [comment]
I've done a clean up on the dependencies. I'll be releasing a v16.6.0 soon. Next steps, I'll bump redux, drop support for React versions below v18.0.0, and release v17.0.0 (I might also revisit our build system for this major).

EDIT (April 19th): I'll be away from my keyboard for a few weeks. I Should have somethings end of May.

EDIT (September 11th): I've had other priorities in the past weeks. I'll see what I can do in the coming days.

**Comment by yildirimbayrakci** [comment]
hi, any updates?

**Comment by 100terres** [comment]
@yildirim2189 sorry, I've had other priorities in the past weeks. I'll see what I can do in the upcoming days.

**Comment by 100terres** [comment]
I've opened a PR: https://github.com/hello-pangea/dnd/pull/828

EDIT: It's merged.

**Comment by 100terres** [comment]
I've cut a release. You can update the lib to v17.
