### ISSUE TITLE
How do I handle elements that wrap lines?

### ISSUE THREAD

**Issue by codepandy** [hello-pangea/dnd#749]
The elements in the container can only be one row or one column, if it is discharged horizontally, can it be supported by a newline?
![11122](https://github.com/hello-pangea/dnd/assets/16410281/5f64a0f0-5ba1-4612-b46f-21f1520cf88d)

**Comment by LuisSchweinberger** [comment]
Hey there,

did you already find a way to solve this problem? I'm currently working on a similar feature and am not sure if this library really supports line-wrap.

**Comment by Tomi-Tom** [comment]
Hello there,
Are there any updates?

**Comment by 100terres** [comment]
For now only vertical and horizontal lists without wrapping are supported.
