### ISSUE TITLE
Usage with React Flow

### ISSUE THREAD

**Issue by wildsonc** [hello-pangea/dnd#774]
I'm trying to use DnD within a [react-flow](https://reactflow.dev/) node, but scale and transform added in css by flow broke DnD computed sizes, I believe the main problem is the scale. I tried using portal but without the scale everything looks very strange because it changes the size, what else can I try?

![CleanShot 2024-03-30 at 19 59 20](https://github.com/hello-pangea/dnd/assets/72408418/13e48238-361b-44f1-85c5-0823e38232db)
In the example above it is with "position: static", without it when I move the element it goes very far away.

### Demo

https://codesandbox.io/p/sandbox/dnd-with-scale-kcgv4h?file=%2Fsrc%2FApp.tsx%3A35%2C1

**Comment by denishsharma** [comment]
@wildsonc did you find any solution? I am running into similar situation.
