### ISSUE TITLE
Constraining movement axis? - Browser tabs

### ISSUE THREAD

**Issue by schwjustin** [hello-pangea/dnd#795]
### Description

Is it possible to constrain the movement of Draggable items (only x-axis or y-axis)? The use case is making tabs similar to Chrome or Safari where you can drag to move tabs but they only move on the x-axis. If not, is it feasible to implement this feature? Thanks.

**Comment by erwol** [comment]
Short answer: no as the library is based in the HTML5 drag and drop functionality which does not support this.

Long answer: some workarounds were proposed in this thread from the original `react-beautiful-dnd` repository: https://github.com/atlassian/react-beautiful-dnd/issues/958.

**Comment by 100terres** [comment]
Won't be something we support.

see: https://github.com/atlassian/react-beautiful-dnd/issues/958#issuecomment-441846752
> > ### Application 5: no drag axis locking
> > For now, the library does not support drag axis locking (aka drag rails). This is where the user is restricted to only dragging along one axis. The current thinking is this breaks the physical metaphor we are going for and sends a message to the user that they are interacting with a piece of software rather than moving physical objects around. It is possible to ensure that a user can only drop in a single list by using props type and isDropDisabled. You can also do some visual treatment to the list onDragStart to show the user that this is the only place they can interact with.
> 
> You are welcome to add this on top of the library as you are. However, there might be some rough edges.

Thank you for suggesting.

**Comment by Ahmed-Dghaies** [comment]
You can add this to your Draggable for vertical drag only
```
    let transform = provided.draggableProps.style?.transform;

    if (transform) {
      transform = transform.replace(
        /translate\((-?\d+)px, (-?\d+)px\)/,
        "translate(0px, $2px)"
      );
      provided.draggableProps.style = {
        ...provided.draggableProps.style,
        transform,
      };
    }
```
for horizental 
```
    transform = transform.replace(/,\s[-+]*\d+px\)/, ", 0px)");
```
